#!/bin/sh

current_dir=$(dirname $0)
cd "$current_dir"
source $current_dir/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
echo "T" > "$PANEL_FIFO" &
conky -qc ./panel_conky > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | $current_dir/panel_bar \
    | lemonbar \
        -f "$FONT1","$FONT2" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" \
        -g "$PANEL_GEOMETRY" \
        -u $LINEHEIGHT \
    | sh &

wait
